/**
 * Literature module — shared types + pure helpers for the static poem corpus.
 *
 * The corpus (poems, writers, types) is an immutable, shared, non-private STATIC ASSET under
 * `public/literature/**` (generated by `scripts/build-literature-data.mjs`), not a Postgres table —
 * so browsing/search/filter run fully offline with no DB cost. Only per-user favourites + read-aloud
 * settings live in Supabase. Search/filter is therefore client-side over the in-memory index, using
 * the always-resident `foldZh` (Traditional⇄Simplified-agnostic), matching the Quotes Library.
 */
import { foldZh } from './zh-fold'

// --- static-asset shapes (follow scripts/build-literature-data.mjs output) ----------------------

export type TypeKind = 'theme' | 'season' | 'anthology' | 'style' | 'other'

/** A curated filter value (主題/時令/選集/風格). `other` types exist in the data but aren't shown as filters. */
export interface LiteratureType {
  id: number
  name: string
  kind: TypeKind
  sortOrder: number
}

/** Lightweight writer row for the Poets grouping screen (full bio is in writer/<id>.json). */
export interface WriterLite {
  id: number
  name: string
  dynasty: string | null
}

export interface LiteratureMeta {
  version: number
  types: LiteratureType[]
  writers: WriterLite[]
  dynasties: string[]
}

/** A poem-list card renders entirely from this — no body fetch needed. */
export interface PoemIndexEntry {
  id: number
  title: string
  writerId: number
  writer: string
  dynasty: string | null
  typeIds: number[]
  excerpt: string
}

export interface PoemDetail {
  id: number
  title: string
  writer: string
  writerId: number
  dynasty: string | null
  content: string
  translation: string | null
  remark: string | null
  shangxi: string | null
  typeIds: number[]
}

export interface WriterDetail {
  id: number
  name: string
  dynasty: string | null
  simpleIntro: string | null
  detailIntro: string | null
  headImageUrl: string | null
  poemIds: number[]
}

// --- read-aloud --------------------------------------------------------------------------------

/** zh-HK = 粵 (Cantonese) · zh-CN = 國 (Mandarin). Stored in profile.literature_tts_lang. */
export type SpeechLang = 'zh-HK' | 'zh-CN'

export const SPEECH_LANG_OPTIONS: { value: SpeechLang; label: string }[] = [
  { value: 'zh-HK', label: '粵' },
  { value: 'zh-CN', label: '國' },
]

// --- list criteria -----------------------------------------------------------------------------

/** Poem-list sort field (follows the Library Sort menu). */
export type PoemSortField = 'dynasty' | 'author' | 'title'
export type SortDir = 'asc' | 'desc'

/** Poem search + filter + sort state. Held in `useSessionState` so it survives drill-in/back. */
export interface PoemCriteria {
  query: string
  /** Selected dynasty (exact match on the poem's dynasty), or null for any. */
  dynasty: string | null
  /** Selected type ids (主題/時令/選集): OR within a kind-group, AND across groups. */
  typeIds: number[]
  favoritesOnly: boolean
  sortField: PoemSortField
  sortDir: SortDir
}

export const DEFAULT_POEM_CRITERIA: PoemCriteria = {
  query: '',
  dynasty: null,
  typeIds: [],
  favoritesOnly: false,
  sortField: 'dynasty',
  sortDir: 'asc',
}

// --- per-field visibility (Settings → 顯示) -----------------------------------------------------

/**
 * Toggleable poem-detail sections, stored on `profile.literature_poem_visible_fields` (NULL = all
 * visible). 原文 (the poem body) is always shown and is not listed here.
 */
export const POEM_VISIBLE_FIELDS: { key: string; label: string }[] = [
  { key: 'translation', label: '譯文' },
  { key: 'remark', label: '註釋' },
  { key: 'shangxi', label: '賞析' },
]

/**
 * Toggleable poet-detail sections, stored on `profile.literature_writer_visible_fields` (NULL = all
 * visible). 作品 (the works list) is always shown and is not listed here.
 */
export const WRITER_VISIBLE_FIELDS: { key: string; label: string }[] = [
  { key: 'bio', label: '作者簡介' },
]

/** NULL prefs ⇒ every field visible (default-on); otherwise an explicit allow-list. */
export function isFieldVisible(visibleFields: string[] | null, key: string): boolean {
  return visibleFields == null || visibleFields.includes(key)
}

// --- filtering ---------------------------------------------------------------------------------

/**
 * Group selected type ids by their kind, so the filter is OR-within-a-group, AND-across-groups —
 * e.g. (春 OR 秋) AND 唐詩三百首. Unknown ids (not in `typesById`) are ignored.
 */
function selectedByKind(
  typeIds: number[],
  typesById: Map<number, LiteratureType>,
): Map<TypeKind, Set<number>> {
  const groups = new Map<TypeKind, Set<number>>()
  for (const id of typeIds) {
    const t = typesById.get(id)
    if (!t) continue
    const set = groups.get(t.kind) ?? new Set<number>()
    set.add(id)
    groups.set(t.kind, set)
  }
  return groups
}

export interface HomeViewContext {
  typesById: Map<number, LiteratureType>
  favoriteIds: Set<number>
}

/** Apply search + filters to the poem index (client-side; the index is small + in memory). */
export function applyPoemView(
  index: PoemIndexEntry[],
  c: PoemCriteria,
  ctx: HomeViewContext,
): PoemIndexEntry[] {
  const q = foldZh(c.query.trim())
  const groups = c.typeIds.length ? selectedByKind(c.typeIds, ctx.typesById) : null

  return index.filter((p) => {
    if (c.favoritesOnly && !ctx.favoriteIds.has(p.id)) return false
    if (c.dynasty && p.dynasty !== c.dynasty) return false
    if (q) {
      const hay = foldZh(`${p.title} ${p.writer} ${p.excerpt}`)
      if (!hay.includes(q)) return false
    }
    if (groups) {
      for (const ids of groups.values()) {
        // AND across groups: the poem must carry at least one selected type from each group.
        if (!p.typeIds.some((id) => ids.has(id))) return false
      }
    }
    return true
  })
}

// --- sorting -----------------------------------------------------------------------------------

function poemSortKey(
  p: PoemIndexEntry,
  field: PoemSortField,
  rank: Map<string, number>,
): string | number | null {
  switch (field) {
    case 'dynasty': {
      // Chronological by the corpus dynasty order (oldest→newest); null/unknown sorts last.
      if (p.dynasty == null) return null
      return rank.get(p.dynasty) ?? null
    }
    case 'author':
      return p.writer.toLowerCase()
    case 'title':
      return p.title.toLowerCase()
  }
}

function comparePoems(
  a: PoemIndexEntry,
  b: PoemIndexEntry,
  field: PoemSortField,
  dir: SortDir,
  rank: Map<string, number>,
): number {
  const ka = poemSortKey(a, field, rank)
  const kb = poemSortKey(b, field, rank)
  // Missing values always sort last, regardless of direction.
  if (ka == null && kb == null) return a.title.localeCompare(b.title)
  if (ka == null) return 1
  if (kb == null) return -1
  const primary =
    typeof ka === 'number' && typeof kb === 'number'
      ? ka - kb
      : String(ka).localeCompare(String(kb))
  if (primary !== 0) return dir === 'asc' ? primary : -primary
  return a.title.localeCompare(b.title) // stable tiebreak
}

/**
 * Sort a (already-filtered) poem list by field + direction. Pure — copies before sorting.
 * `dynastyOrder` is `meta.dynasties` (already chronological), so the dynasty sort is corpus-consistent.
 */
export function sortPoems(
  poems: PoemIndexEntry[],
  field: PoemSortField,
  dir: SortDir,
  dynastyOrder: string[],
): PoemIndexEntry[] {
  const rank = new Map(dynastyOrder.map((d, i) => [d, i]))
  return [...poems].sort((a, b) => comparePoems(a, b, field, dir, rank))
}

/** Writers grouped by dynasty for the Poets screen, in the corpus's dynasty order. */
export function groupWritersByDynasty(
  writers: WriterLite[],
  dynastyOrder: string[],
): { dynasty: string; writers: WriterLite[] }[] {
  const rank = new Map(dynastyOrder.map((d, i) => [d, i]))
  const byDynasty = new Map<string, WriterLite[]>()
  for (const w of writers) {
    const key = w.dynasty ?? '其他'
    const arr = byDynasty.get(key) ?? []
    arr.push(w)
    byDynasty.set(key, arr)
  }
  return [...byDynasty.entries()]
    .sort(
      (a, b) =>
        (rank.get(a[0]) ?? 999) - (rank.get(b[0]) ?? 999) || a[0].localeCompare(b[0]),
    )
    .map(([dynasty, ws]) => ({
      dynasty,
      writers: ws.sort((a, b) => a.name.localeCompare(b.name)),
    }))
}
