import { createBrowserRouter } from 'react-router'
import { RequireAuth } from './auth/RequireAuth'
import { AppShell } from './components/AppShell'
import {
  Login,
  Home,
  RootRedirect,
  Settings,
  VisibleModulesSheet,
  WellnessDashboard,
  WellnessDiary,
  WellnessDailyReportSheet,
  WellnessLibrary,
  WellnessFoodAddSheet,
  WellnessFoodNewSheet,
  WellnessFoodSheet,
  WellnessActivityAddSheet,
  WellnessActivityNewSheet,
  WellnessActivitySheet,
  WellnessSettings,
  WellnessHighlightedNutrientsSheet,
  WellnessVisibleNutrientsSheet,
  ImportFoodsSheet,
  BooksDashboard,
  BooksLibrary,
  BooksEntry,
  BooksSettings,
  BooksFieldsSheet,
  ImportBooksSheet,
  LiteraturePoems,
  LiteraturePoemDetail,
  LiteraturePoets,
  LiteraturePoetDetail,
  LiteratureSettings,
  LiteraturePoemFieldsSheet,
  LiteratureWriterFieldsSheet,
  MedicalDashboard,
  MedicalEntry,
  MedicalReports,
  MedicalReportDetail,
  MedicalSettings,
  MedicalFieldsSheet,
  MedicalTrackedTestsSheet,
  MedicalOrderSheet,
  MedicalLockSheet,
  ImportMedicalSheet,
  NetWorthDashboard,
  NetWorthFundDetailSheet,
  NetWorthEntry,
  NetWorthSettings,
  NetWorthVisibleAssetTypesSheet,
  NetWorthLiquidAssetTypesSheet,
  InsurancePolicies,
  InsuranceEntry,
  InsurancePolicyDetailSheet,
  InsuranceProvidersSheet,
  ImportNetWorthSheet,
  ImportFundSheet,
  ImportInsuranceBulkSheet,
  QuotesZen,
  QuotesLibrary,
  QuotesEntry,
  QuotesSettings,
  QuotesFieldsSheet,
  QuoteSourceTypesSheet,
  QuoteCategoriesSheet,
  ImportQuotesSheet,
  ShowsDashboard,
  ShowsLibrary,
  ShowsEntry,
  ShowsSettings,
  ShowsFieldsSheet,
  ImportShowsSheet,
  TravelDashboard,
  TravelMap,
  TravelTrips,
  TravelEntry,
  TravelSettings,
  TravelFieldsSheet,
  TravelCategoriesSheet,
  ImportTravelSheet,
  ImportTravelExpensesSheet,
} from './screens'

// Routes are flat children of the single <AppShell/> layout (full path strings, no
// nested layout route) so the background-location sheet pattern + single <Outlet/> are
// unchanged. Modules are URL-namespaced (/wellness/*, /networth/*); see constants/routes.ts.
export const router = createBrowserRouter([
  { path: '/login', element: <Login /> },
  {
    element: <RequireAuth />,
    children: [
      {
        element: <AppShell />,
        children: [
          // Home hub + global settings
          { index: true, element: <RootRedirect /> },
          { path: 'home', element: <Home /> },
          { path: 'settings', element: <Settings /> },
          { path: 'settings/visible-modules', element: <VisibleModulesSheet /> },

          // Wellness module — tabs
          { path: 'wellness', element: <WellnessDiary /> },
          { path: 'wellness/dashboard', element: <WellnessDashboard /> },
          { path: 'wellness/report/:day', element: <WellnessDailyReportSheet /> },
          { path: 'wellness/library', element: <WellnessLibrary /> },
          { path: 'wellness/add-food', element: <WellnessFoodAddSheet /> },
          { path: 'wellness/new-food', element: <WellnessFoodNewSheet /> },
          { path: 'wellness/edit-food/:id', element: <WellnessFoodNewSheet /> },
          { path: 'wellness/food/:source/:id', element: <WellnessFoodSheet /> },
          { path: 'wellness/add-activity', element: <WellnessActivityAddSheet /> },
          { path: 'wellness/new-activity', element: <WellnessActivityNewSheet /> },
          { path: 'wellness/edit-activity/:id', element: <WellnessActivityNewSheet /> },
          { path: 'wellness/activity/:activityId', element: <WellnessActivitySheet /> },
          { path: 'wellness/settings', element: <WellnessSettings /> },
          {
            path: 'wellness/settings/visible',
            element: <WellnessVisibleNutrientsSheet />,
          },
          {
            path: 'wellness/settings/highlighted',
            element: <WellnessHighlightedNutrientsSheet />,
          },
          { path: 'wellness/import-foods', element: <ImportFoodsSheet /> },

          // Net Worth module
          { path: 'networth', element: <NetWorthDashboard /> },
          { path: 'networth/fund/:id', element: <NetWorthFundDetailSheet /> },
          { path: 'networth/policy/:id', element: <InsurancePolicyDetailSheet /> },
          { path: 'networth/entry', element: <NetWorthEntry /> },
          { path: 'networth/insurance', element: <InsurancePolicies /> },
          { path: 'networth/insurance/new', element: <InsuranceEntry /> },
          { path: 'networth/insurance/:id', element: <InsuranceEntry /> },
          { path: 'networth/settings', element: <NetWorthSettings /> },
          {
            path: 'networth/settings/asset-types',
            element: <NetWorthVisibleAssetTypesSheet />,
          },
          {
            path: 'networth/settings/liquid-types',
            element: <NetWorthLiquidAssetTypesSheet />,
          },
          { path: 'networth/settings/providers', element: <InsuranceProvidersSheet /> },
          { path: 'networth/import', element: <ImportNetWorthSheet /> },
          { path: 'networth/import-fund', element: <ImportFundSheet /> },
          { path: 'networth/import-insurance', element: <ImportInsuranceBulkSheet /> },

          // Shows module
          { path: 'shows', element: <ShowsDashboard /> },
          { path: 'shows/library', element: <ShowsLibrary /> },
          { path: 'shows/entry', element: <ShowsEntry /> },
          { path: 'shows/:id', element: <ShowsEntry /> },
          { path: 'shows/settings', element: <ShowsSettings /> },
          { path: 'shows/settings/visible', element: <ShowsFieldsSheet /> },
          { path: 'shows/import', element: <ImportShowsSheet /> },

          // Books module
          { path: 'books', element: <BooksDashboard /> },
          { path: 'books/library', element: <BooksLibrary /> },
          { path: 'books/entry', element: <BooksEntry /> },
          { path: 'books/:id', element: <BooksEntry /> },
          { path: 'books/settings', element: <BooksSettings /> },
          { path: 'books/settings/visible', element: <BooksFieldsSheet /> },
          { path: 'books/import', element: <ImportBooksSheet /> },

          // Quotes module
          { path: 'quotes', element: <QuotesZen /> },
          { path: 'quotes/library', element: <QuotesLibrary /> },
          { path: 'quotes/entry', element: <QuotesEntry /> },
          { path: 'quotes/:id', element: <QuotesEntry /> },
          { path: 'quotes/settings', element: <QuotesSettings /> },
          { path: 'quotes/settings/visible', element: <QuotesFieldsSheet /> },
          { path: 'quotes/settings/source-types', element: <QuoteSourceTypesSheet /> },
          { path: 'quotes/settings/categories', element: <QuoteCategoriesSheet /> },
          { path: 'quotes/import', element: <ImportQuotesSheet /> },

          // Literature module — tabs + drill-in detail screens (corpus is a static asset)
          { path: 'literature', element: <LiteraturePoems /> },
          { path: 'literature/poem/:id', element: <LiteraturePoemDetail /> },
          { path: 'literature/poets', element: <LiteraturePoets /> },
          { path: 'literature/poet/:id', element: <LiteraturePoetDetail /> },
          { path: 'literature/settings', element: <LiteratureSettings /> },
          {
            path: 'literature/settings/visible-poem',
            element: <LiteraturePoemFieldsSheet />,
          },
          {
            path: 'literature/settings/visible-writer',
            element: <LiteratureWriterFieldsSheet />,
          },

          // Medical module
          { path: 'medical', element: <MedicalDashboard /> },
          { path: 'medical/reports', element: <MedicalReports /> },
          { path: 'medical/entry', element: <MedicalEntry /> },
          { path: 'medical/:id', element: <MedicalReportDetail /> },
          { path: 'medical/:id/edit', element: <MedicalEntry /> },
          { path: 'medical/settings', element: <MedicalSettings /> },
          { path: 'medical/settings/visible', element: <MedicalFieldsSheet /> },
          { path: 'medical/settings/tracked', element: <MedicalTrackedTestsSheet /> },
          { path: 'medical/settings/order', element: <MedicalOrderSheet /> },
          { path: 'medical/settings/lock', element: <MedicalLockSheet /> },
          { path: 'medical/import', element: <ImportMedicalSheet /> },

          // Travel module
          { path: 'travel', element: <TravelDashboard /> },
          { path: 'travel/map', element: <TravelMap /> },
          { path: 'travel/trips', element: <TravelTrips /> },
          { path: 'travel/entry', element: <TravelEntry /> },
          { path: 'travel/trip/:id', element: <TravelEntry /> },
          { path: 'travel/settings', element: <TravelSettings /> },
          { path: 'travel/settings/visible', element: <TravelFieldsSheet /> },
          { path: 'travel/settings/categories', element: <TravelCategoriesSheet /> },
          { path: 'travel/import-travel', element: <ImportTravelSheet /> },
          { path: 'travel/import-expenses', element: <ImportTravelExpensesSheet /> },
        ],
      },
    ],
  },
])
